### PR TITLE
Put actual license in LICENSE file

### PR DESCRIPTION
**Pull request by tarsius**
Previously it contained just a permission statement.  That permission
statement also serves a purpose, but it should be added to the header
of actual source files.  This commit does that too.

### CODE REVIEW

**Comment by crocket** [comment]
The legal language in GPLv2 makes me dizzy. But, I am going to merge it.

**Comment by tarsius** [comment]
Thanks!

**Comment by crocket** [comment]
In the past, I forked a project with MIT license and removed authors from LICENSE by mistake.
I announced the fork. People burned me for removing authors.

This is GPL which may be different from MIT.
However, it might burn me or us in the future.

Honestly, I do not want to think about the legal mess of copyright.
If you or anyone else cared to fix it, I'll merge.

**Comment by tarsius** [comment]
These lines are still in the library, so I don't think this is a problem.

**Pull request merged**
